### ISSUE TITLE
Missing: require('os').homedir

### ISSUE THREAD

**Issue by steven10172** [CoderPuppy/os-browserify#7]
The homedir() method is missing

**Comment by CoderPuppy** [comment]
Could you explain what you're using it for?

**Comment by steven10172** [comment]
I technically no longer need it, the logic has been moved to a server. Originally I was running the lock file parser from yarn in the browser. That method wasn't being used for anything, but one of the webpack modules had that line in it and would fail when evaluating.

As a temporary work around I just told webpack 'os' was an alias to a specific file that just re-mocked everything.

**Comment by CoderPuppy** [comment]
~~So would something like `os.homedir = function() {}` would be fine? Or does it need to return a string?~~
Just looking around it looks like it needs to return a string, so I'll do `/`.
